---
bundle_install: false
bundle_install_folder: "/var/lib/ansible-automation-platform-bundle"

# Indicate the path to the subscription-manager repository file
redhat_rhsm_repo_path: '/etc/yum.repos.d/redhat.repo'

# Specify RHEL subscription-manager repositories to enable (used in vars/*.yml).
redhat_rhsm_repos: []

ansible_automation_platform_repo: ansible-automation-platform
automation_controller_repo: automation-controller

# Pre-defined dynamically determined variables to satisfy ansible 1.9 and ansible 2.0 deprecation warnings
yum_repo_keys:
  - 'RPM-GPG-KEY-redhat-release'

# Indicate whether to verify gpg signatures during install
gpgcheck: 1
