---
- name: Copy custom CA cert
  copy:
    src: "{{ custom_ca_cert }}"
    dest: "/etc/pki/ca-trust/source/anchors/ansible-automation-platform-custom-ca-cert.crt"
    mode: '0644'
    owner: root
    group: root
  notify: Update CA trust
