---
el_dependencies:
  - python3-psycopg2
  - python3-setuptools
  - python3-libselinux
  - python3-setools
  - python3-cryptography
  - dnf-utils
  - sudo
  - acl

dnf_modules:
  - 'nginx:1.18'
  - 'python38'

dnf_modules_disable:
  - 'php'

postgresql_packages:
  - postgresql-contrib
  - postgresql-server

upgrade_postgres: false

existing_pg_dir: '/var/lib/pgsql/data'
