---
# Auto is more robust for us than auto_legacy (still the default as of 2.8)
# because the geerlingguy.postgresql role, with RPM weak deps, installs
# /usr/bin/python pointing to python2, on Fedora 30. This in turn breaks
# running pulp_installer a 2nd time, because F30 lacks python2-dnf.
ansible_python_interpreter: auto

pulp_rhel7_scl_repo:
  - rhui-rhel-server-rhui-rhscl-7-rpms  # seen on RHEL7.7 on AWS
  - rhel-server-rhscl-7-rpms
  - rhel-workstation-rhscl-7-rpms
