---
# Django Options
admin_username: admin
admin_email: admin@example.com

# Params
awx_install_pg_init_name: None

# SSL CA trust store
ca_trust_bundle: '/etc/pki/tls/certs/ca-bundle.crt'

# Default image for containerized job runs
container_groups_image: "{{ _ee_image_base }}ee-supported-rhel8:latest"

# Default url for uploads to automation analytics
automation_analytics_url: 'https://cloud.redhat.com/api/ingress/v1/upload'

global_job_execution_environments:
  - name: "Default execution environment"
    image: "{{ _ee_image_base }}ee-supported-rhel8:latest"
  - name: "Ansible Engine 2.9 execution environment"
    image: "{{ _ee_image_base }}ee-29-rhel8:latest"
  - name: "Minimal execution environment"
    image: "{{ _ee_image_base }}ee-minimal-rhel8:latest"

control_plane_execution_environment: "{{ _ee_image_base }}ee-supported-rhel8:latest"
